### PR TITLE
fix(images): actually call on_clear callback in BufferCache

### PR DESCRIPTION
**Pull request by PaulHax**

### CODE REVIEW

**Comment by vicentebolea** [comment]
rebase will fix the ci

**Comment by PaulHax** [comment]
I could.  Do we want to move the converstation of #88 here.  With the blanket branch protection rules, I can't push updates to the `all-images` branch in #88.

**Comment by vicentebolea** [comment]
Oh @PaulHax I removed the rule, I Was trying to protect the branches since I was testing automatically merging release into master.

**Comment by PaulHax** [comment]
Just made changes to the `all-images` branch in #88 and this PR is not needed.

**Pull request closed without merging**
