### PR TITLE
Place code under src dir and use hatchling for building

### PR DESCRIPTION
**Pull request by alesgenova**

### CODE REVIEW

**Comment by vicentebolea** [comment]
@alesgenova this looks good in principles. I Wonder what is the reason of moving python bits to src and why not to crash (print help) when wrong arguments are passed.

**Comment by alesgenova** [comment]
> @alesgenova this looks good in principles. I Wonder what is the reason of moving python bits to src and why not to crash (print help) when wrong arguments are passed.

The reason for the rearrangement is that it makes the git repo a package that can be pip installed properly when running `pip install .` without the `-e` option.

The reason for ignoring the unknown parameters, is that when running it in some jupyter environments we get passed some parameters we don't have control over

**Comment by vicentebolea** [comment]
Make sense. Would it make sense to rename src to python, so that vue code is in the vue-component and python in python dir?

We probably want to revisit later about the cli arguments part, I understand that we are in a hurry now. Ignoring wrong args sound like a recipe for users getting confused of which argument works or not, perhaps we can add a flag that says "hey ignore following arguments" later on

**Comment by jourdain** [comment]
LGTM

**Review by vicentebolea — APPROVED** [review]

**Pull request merged**
