### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by jourdain** [comment]
Will go through some obvious cleanup and then I would like to clean some logic. But one step at a time. ;-)

**Comment by jourdain** [comment]
FYI @PaulHax

**Comment by PaulHax** [comment]
Good stuff.  I rearanged alot of the logic mess into a new mess in #88 .  Maybe hold messing with internal applet logic for a bit or start from #88 
🙏

**Comment by jourdain** [comment]
yes I saw that is why we should get yours merged sometime tomorrow

**Review by PaulHax — APPROVED** [review]
First step good to go?

**Comment by jourdain** [comment]
I have some following stuff that I will push soon

**Comment by jourdain** [comment]
@PaulHax did my pass but now looking at `nrtk_explorer/app/ui/image_list.py`... And I really don't like those global things... I guess I need to get a better grasp before editing anything, but it might be worth chatting about it at some point.

**Review by PaulHax — APPROVED** [review]
yay

**Pull request merged**
