### PR TITLE
ci: add flake8 tests

### PR DESCRIPTION
**Pull request by vicentebolea**

### CODE REVIEW

**Comment by vicentebolea** [comment]
@alesgenova

**Comment by jcfr** [comment]
I suggest to adopt ruff instead of the obsolete flake8. 

You may be interested in https://learn.scientific-python.org/ where we maintain templates:
* https://learn.scientific-python.org/development/guides/
* https://github.com/scientific-python/cookie

**Comment by vicentebolea** [comment]
Thanks for the suggestion. I must ask, how is flake8 obsolete? I can see that they support py 3.12 it is actively maintained, plus it seems to be still the "industry" standard for linting python code.

**Comment by jcfr** [comment]
> obsolete

What I meant is that considering that all[^1] rules have been have been implemented in Ruff, explicitly integrating flake8 tooling should be considered an obsolete practice.

[^1]: https://docs.astral.sh/ruff/rules/

**Comment by vicentebolea** [comment]
> explicitly integrating flake8 tooling should be considered an obsolete practice

I understand that ruff has been chosen as the linting tool for scientific python cookie, this does not make using flake8 as an obsolete practice across python projects.

In any case, the feature is already developed in this PR, I am happy to move to something else if needed but I suggest to bring this to a discussion after merging this so we have linting asap.

**Comment by jcfr** [comment]
I just wanted to point out that some useful resources intended to streamline over development, this should now prevent you from moving forward with this PR. Considering `@` in the relevant discussion.

**Comment by vicentebolea** [comment]
@jcfr thanks for bringing ideas to help us with the development of this project. I am sure that ruff is a much better alternative, I was genuinely curious about the rationale of the claim as I could see some other big python project persisting in their use of flake8 and others versus ruff. Lets explore this later!

**Review by alesgenova — APPROVED** [review]

**Pull request merged**
