### PR TITLE
Rework image storage scheme

### PR DESCRIPTION
**Pull request by vicentebolea**
In this PR I add several things:

- I extracted the bits from #41 to make sure that we work with visdrone dataset (fixed image id selection).
- I reworked how we resize images and the different type of images that we save, I change the schema of image types and sizes that we store as shown in the diagram below.
- I heavily refactored image_manager module.
- ~I added the commit from #43 to fix reactivity so we can have all the changes in one go.~

```mermaid
graph TD;
    OriginalImage-->Thumbnail;
    OriginalImage--->OriginalTransformation;
    Thumbnail-->ImageForModel;
    Thumbnail-->ThumbnailTransformation;
    ThumbnailTransformation-->TransformationForModel;
```

### CODE REVIEW

**Comment by vicentebolea** [comment]
This superseeds #41 and #43

**Comment by alesgenova** [comment]
I'm not sure about generating the transformed images based on the thumbnail of the original image.
What do you think about a relation like this? We would only do the transformation once, and all the other images are created by resize operations

```mermaid
graph TD;
    OriginalImage-->|resize|OriginalThumbnail;
    OriginalImage-->|resize|OriginalForModel;
    TransformedImage-->|resize|TransformedThumbnail;
    TransformedImage-->|resize|TransformedForModel;
    OriginalImage---|transform|TransformedImage;
```

**Comment by vicentebolea** [comment]
Performance is the reason for this. Transformation of full size image some of them are over FHD can be quite slow. And we do not need them anyways since we always run the model with the downsized images. If the user wants to download the full size transformation we can always generate for the particular image he is interested on.

**Comment by vicentebolea** [comment]
I should have explain that we do not make the transformation of the full sized image unless requested (not implemented yet the feature of downloading transformations)

**Review by alesgenova — APPROVED** [review]

**Pull request merged**
