### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by Erotemic**
One of the steps not listed in the README is ensuring that npm is installed. In an effort to not make the README too big, I've added a `docs` subfolder. I initialized this using xcookie, which builds standard sphinx auto-API documentation. In addition I add a "manual" directory where long rst files can be written. I wrote `DEVELOPMENT.rst` with instructions for an npm install and placed it there, and I also linked to it in the README.

There are improvements that could be made, but this helps setup the scaffolding.

### CODE REVIEW

**Review by jourdain — APPROVED** [review]

**Comment by jourdain** [comment]
@Erotemic can you make sure to use semantic-release commit message style. `docs(sphinx): ...`

**Comment by Erotemic** [comment]
Commit messages have been cleaned up.

**Comment by jourdain** [comment]
You may want to install the pre-commit hooks to fix the ci. (formatting of the conf.py)

**Comment by Erotemic** [comment]
Done. I should probably add pre-commit hooks to my workflow. Just using it for codespell seems worth it.

Note the conf.py is autogenerated by xcookie, and contains a lot more than it needs to for this. This could be removed and then the sphinx conf could be managed manually. The main feature the extra code adds is the ability to grab any images created in doctests and then add them to the readthedocs as [demonstrated by kwimage](https://kwimage.readthedocs.io/en/release/kwimage.html#kwimage.nodata_checkerboard).

**Pull request merged**
